[build-system]
requires = [
  'setuptools >= 40.9.0',
  'wheel',
]
build-backend = 'setuptools.build_meta'

[tool.black]
line-length = 79

[tool.isort]
profile = 'black'
line_length = 79
lines_after_imports = 2
combine_as_imports = true
